package General;

import Utilities.FileHandling;
import Utilities.UserRegistrationInfo;
import java.io.File;
import java.io.IOException;
import javax.swing.JFrame;

public class ManagerProfile extends javax.swing.JFrame {

    UserRegistrationInfo mgr = new UserRegistrationInfo();
    
    public ManagerProfile(String userID, String userPassword) {
        initComponents();
        setTitle("APU Cafeteria Ordering System");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setVisible(true);
        mgr.setUserID(userID);
        mgr.setUserPassword(userPassword);
        
        //For Dispalying the Current Balance
        String line = "";
        FileHandling custFile = new FileHandling();
        File file = new File("mgrAccount.txt");
        try {
            //Locates line in file and stores in variable
            line = custFile.locateItemInFile(mgr.getUserID(), file, 0);
        } catch (IOException e) {
            System.err.println("Exception occurred - " + e.toString());
        }
        
        //Splits line into multiple sections
        String [] section = line.split("\\|");
        
        //Sets the manager credentials iwthin the text fields
        mgrID.setText(userID);
        mgrName.setText(section[1]);
        mgrPassword.setText(userPassword);
        mgrEmail.setText(section[3]);
        
        //Ensures textfields cannot be edited
        mgrID.setEditable(false);
        mgrName.setEditable(false);
        mgrPassword.setEditable(false);
        mgrEmail.setEditable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        mgrBackBtn = new javax.swing.JButton();
        mgrEmail = new javax.swing.JTextField();
        custEmailLabel = new javax.swing.JLabel();
        showPassword = new javax.swing.JCheckBox();
        mgrPassword = new javax.swing.JPasswordField();
        custPasswordLabel = new javax.swing.JLabel();
        mgrName = new javax.swing.JTextField();
        custNameLabel = new javax.swing.JLabel();
        mgrID = new javax.swing.JTextField();
        custIDLabel1 = new javax.swing.JLabel();
        custHomeHeader2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(244, 244, 244));
        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mgrBackBtn.setFont(new java.awt.Font("SF Pro Text", 1, 14)); // NOI18N
        mgrBackBtn.setForeground(new java.awt.Color(255, 0, 0));
        mgrBackBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        mgrBackBtn.setText("BACK");
        mgrBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mgrBackBtnActionPerformed(evt);
            }
        });
        jPanel1.add(mgrBackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 597, -1, 40));

        mgrEmail.setBackground(new java.awt.Color(244, 244, 244));
        mgrEmail.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        mgrEmail.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mgrEmail.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(244, 244, 244)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(244, 244, 244))); // NOI18N
        jPanel1.add(mgrEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 528, 300, 36));

        custEmailLabel.setBackground(new java.awt.Color(0, 0, 0));
        custEmailLabel.setFont(new java.awt.Font("SF Pro Text", 1, 18)); // NOI18N
        custEmailLabel.setForeground(new java.awt.Color(255, 255, 255));
        custEmailLabel.setText("Email:");
        jPanel1.add(custEmailLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 529, -1, 31));

        showPassword.setForeground(new java.awt.Color(255, 255, 255));
        showPassword.setText("Show Password");
        showPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showPasswordActionPerformed(evt);
            }
        });
        jPanel1.add(showPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 496, -1, -1));

        mgrPassword.setBackground(new java.awt.Color(244, 244, 244));
        mgrPassword.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mgrPassword.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(244, 244, 244))); // NOI18N
        jPanel1.add(mgrPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 361, 300, 35));

        custPasswordLabel.setBackground(new java.awt.Color(0, 0, 0));
        custPasswordLabel.setFont(new java.awt.Font("SF Pro Text", 1, 18)); // NOI18N
        custPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        custPasswordLabel.setText("Password:");
        jPanel1.add(custPasswordLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 419, -1, 35));

        mgrName.setBackground(new java.awt.Color(244, 244, 244));
        mgrName.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        mgrName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mgrName.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(244, 244, 244)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(244, 244, 244))); // NOI18N
        jPanel1.add(mgrName, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 300, 300, 35));

        custNameLabel.setBackground(new java.awt.Color(0, 0, 0));
        custNameLabel.setFont(new java.awt.Font("SF Pro Text", 1, 18)); // NOI18N
        custNameLabel.setForeground(new java.awt.Color(255, 255, 255));
        custNameLabel.setText("Manager Name:");
        jPanel1.add(custNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 361, -1, 31));

        mgrID.setBackground(new java.awt.Color(244, 244, 244));
        mgrID.setFont(new java.awt.Font("SF Pro Text", 0, 12)); // NOI18N
        mgrID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mgrID.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(244, 244, 244)), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(244, 244, 244))); // NOI18N
        jPanel1.add(mgrID, new org.netbeans.lib.awtextra.AbsoluteConstraints(649, 421, 300, 35));

        custIDLabel1.setBackground(new java.awt.Color(0, 0, 0));
        custIDLabel1.setFont(new java.awt.Font("SF Pro Text", 1, 18)); // NOI18N
        custIDLabel1.setForeground(new java.awt.Color(255, 255, 255));
        custIDLabel1.setText("Manager ID:");
        jPanel1.add(custIDLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 312, -1, 31));

        custHomeHeader2.setFont(new java.awt.Font("SF Pro Text", 1, 48)); // NOI18N
        custHomeHeader2.setForeground(new java.awt.Color(255, 0, 0));
        custHomeHeader2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        custHomeHeader2.setText("MANAGER PROFILE");
        custHomeHeader2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        custHomeHeader2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(custHomeHeader2, new org.netbeans.lib.awtextra.AbsoluteConstraints(282, 60, 776, 144));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home-background-image.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mgrBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mgrBackBtnActionPerformed
        ManagerHome mgrBack = new ManagerHome(mgr.getUserID(), mgr.getUserPassword());
        mgrBack.setVisible(true);
        this.dispose();
        System.out.println("User " + mgr.getUserID() + " has attempted to view Manager Home page.");
    }//GEN-LAST:event_mgrBackBtnActionPerformed

    //Check box button to show and hide the password
    private void showPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showPasswordActionPerformed
        if(showPassword.isSelected()){
            mgrPassword.setEchoChar((char)0); 
        } else {
            mgrPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_showPasswordActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel custEmailLabel;
    private javax.swing.JLabel custHomeHeader2;
    private javax.swing.JLabel custIDLabel1;
    private javax.swing.JLabel custNameLabel;
    private javax.swing.JLabel custPasswordLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton mgrBackBtn;
    private javax.swing.JTextField mgrEmail;
    private javax.swing.JTextField mgrID;
    private javax.swing.JTextField mgrName;
    private javax.swing.JPasswordField mgrPassword;
    private javax.swing.JCheckBox showPassword;
    // End of variables declaration//GEN-END:variables
}
